apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: tekton-chains
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
data:
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.storage: grafeas
  artifacts.pipelinerun.signer: kms
  signers.kms.kmsref: gcpkms://projects/chuangw-test/locations/global/keyRings/test/cryptoKeys/mykey/versions/1
  storage.grafeas.projectid: chuangw-test
  storage.grafeas.noteid: builder-test
  builder.id: testbuilder.com
  artifacts.taskrun.storage: "" # disabled
  artifacts.oci.storage: "" # disabled
